// src/vue-app/src/App.vue
<template>
  <v-app>
    <v-toolbar absolute color="primary" dark app clipped-left></v-toolbar>
    <v-card color="white" class="stock-picker" app clipped-left>
      <v-container fluid>
        <StockPicker/>
      </v-container>
    </v-card>
    <v-content style="padding:0">
      <v-navigation-drawer width="240">
        <v-list>
          <template v-for="(item, index) in items">
            <v-list-tile
              :key="item.title"
              :to="{name: item.route}"
              ripple
              exact
              active-class="active-link"
            >
              <v-list-tile-content>
                <v-list-tile-title>{{ item.title }}</v-list-tile-title>
              </v-list-tile-content>
            </v-list-tile>
            <v-divider :key="index"></v-divider>
          </template>
        </v-list>
      </v-navigation-drawer>
      <main>
        <router-view/>
      </main>
    </v-content>
  </v-app>
</template>

<script>
import StockPicker from "./components/StockPicker";
export default {
  name: "App",
  components: {
    StockPicker
  },
  data() {
    return {
      items: [
        { title: "Returns", route: "Home" },
        { title: "Closing prices", route: "ClosingPrices" }
      ]
    };
  }
};
</script>

<style lang="scss">
.v-toolbar {
  position: static;
}
.stock-picker {
  width: 100%;
  min-height: 64px;
  z-index: 5;
}
.v-content__wrap {
  display: flex;
}
.v-navigation-drawer {
  flex-shrink: 0;
  top: 10px;
  box-shadow: 12px -24px 32px -22px rgba(0, 0, 0, 0.75);
}
main {
  flex-grow: 1;
}
html {
  overflow: auto;
}
</style>

// src/react-app/src/App.js
import React, { Component } from "react";
import StockPicker from "./components/StockPicker";
import StockPriceChart from "./components/StockPriceChart";
import StockVolumeChart from "./components/StockVolumeChart";
import StockReturnChart from "./components/StockReturnChart";
import Paper from "@material-ui/core/Paper";
import ListItem from "@material-ui/core/ListItem";
import ListItemText from "@material-ui/core/ListItemText";
import Drawer from "@material-ui/core/Drawer";
import List from "@material-ui/core/List";
import Divider from "@material-ui/core/Divider";
import CssBaseline from "@material-ui/core/CssBaseline";
import AppBar from "@material-ui/core/AppBar";
import Toolbar from "@material-ui/core/Toolbar";
import Typography from "@material-ui/core/Typography";
import LoadingIndicator from "./components/LoadingIndicator";
import { BrowserRouter, Route, Link } from "react-router-dom";
import { MuiThemeProvider, createMuiTheme } from "@material-ui/core/styles";
import { withStyles } from "@material-ui/core/styles";
import * as ReactRedux from "react-redux";
import "./App.css";
import store from "./store";

const theme = createMuiTheme({
  palette: {
    primary: {
      main: "#313847"
    },
    secondary: {
      main: "#a58100"
    }
  }
});
const drawerWidth = 240;
const styles = theme => ({
  appBarRoot: {},
  appBar: {
    zIndex: theme.zIndex.drawer + 1
  },
  root: {
    display: "flex",
    flexGrow: 1
  },
  drawer: {
    width: drawerWidth,
    flexShrink: 0
  },
  drawerPaper: {
    width: drawerWidth,
    zIndex: 0,
    marginTop: 0,
    top: "auto",
    boxShadow: "12px -24px 32px -22px rgba(0,0,0,0.75)"
  },
  content: {
    flexGrow: 1,
    padding: theme.spacing.unit * 3,
    display: "flex"
  },
  stockPicker: {
    padding: 0
  },
  stockPickerPaper: {
    padding: theme.spacing.unit * 2,
    width: "100%",
    zIndex: 100,
    position: "relative"
  },
  toolbar: theme.mixins.toolbar
});

const menuItems = [
  {
    text: "Returns",
    url: "/"
  },
  {
    text: "Closing prices",
    url: "/closing-prices"
  }
];

class App extends Component {
  render() {
    const { classes } = this.props;

    return (
      <BrowserRouter>
        <MuiThemeProvider theme={theme}>
          <ReactRedux.Provider store={store}>
            <div className={classes.appBarRoot}>
              <CssBaseline />
              <AppBar className={classes.appBar} position="static">
                <Toolbar>
                  <Typography variant="h6" color="inherit" noWrap>
                    Stock returns
                  </Typography>
                </Toolbar>
              </AppBar>
            </div>
            <LoadingIndicator />
            <div className={classes.stockPicker}>
              <Paper elevation={1} className={classes.stockPickerPaper}>
                <StockPicker />
              </Paper>
            </div>

            <div className={classes.root}>
              <Drawer
                className={classes.drawer}
                variant="permanent"
                classes={{
                  paper: classes.drawerPaper
                }}
              >
                <List>
                  {menuItems.map((item, index) => (
                    <div key={item.text}>
                      <ListItem button component={Link} to={item.url}>
                        <ListItemText>{item.text}</ListItemText>
                      </ListItem>
                      <Divider />
                    </div>
                  ))}
                </List>
              </Drawer>
              <main className={classes.content}>
                <Route exact path="/" component={StockReturnChart} />
                <Route
                  exact
                  path="/closing-prices"
                  component={StockPriceChart}
                />
                <Route exact path="/volume" component={StockVolumeChart} />
              </main>
            </div>
          </ReactRedux.Provider>
        </MuiThemeProvider>
      </BrowserRouter>
    );
  }
}

export default withStyles(styles, { withTheme: true })(App);
